/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as LifestyleRouteImport } from './routes/lifestyle'
import { Route as LocationRouteImport } from './routes/location'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PhilosophyRouteImport } from './routes/philosophy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AuthGoogleRouteImport } from './routes/auth/google'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ShopProductIdCustomizeRouteImport } from './routes/shop.$productId.customize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const LifestyleRoute = LifestyleRouteImport.update({
  id: '/lifestyle',
  path: '/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PhilosophyRoute = PhilosophyRouteImport.update({
  id: '/philosophy',
  path: '/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AuthGoogleRoute = AuthGoogleRouteImport.update({
  id: '/auth/google',
  path: '/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/auth/logout',
  path: '/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopProductIdCustomizeRoute = ShopProductIdCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => ShopProductIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/lifestyle': typeof LifestyleRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/philosophy': typeof PhilosophyRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$productId': typeof ShopProductIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shop/$productId/customize': typeof ShopProductIdCustomizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/lifestyle': typeof LifestyleRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/philosophy': typeof PhilosophyRoute
  '/signup': typeof SignupRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$productId': typeof ShopProductIdRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shop/$productId/customize': typeof ShopProductIdCustomizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/customize': typeof CustomizeRoute
  '/lifestyle': typeof LifestyleRoute
  '/location': typeof LocationRoute
  '/login': typeof LoginRoute
  '/overview': typeof OverviewRoute
  '/philosophy': typeof PhilosophyRoute
  '/shop': typeof ShopRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/auth/google': typeof AuthGoogleRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/shop/$productId': typeof ShopProductIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shop/$productId/customize': typeof ShopProductIdCustomizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/customize'
    | '/lifestyle'
    | '/location'
    | '/login'
    | '/overview'
    | '/philosophy'
    | '/shop'
    | '/signup'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/auth/google'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/checkout/success'
    | '/shop/$productId'
    | '/admin/'
    | '/shop/'
    | '/api/auth/$'
    | '/shop/$productId/customize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/customize'
    | '/lifestyle'
    | '/location'
    | '/login'
    | '/overview'
    | '/philosophy'
    | '/signup'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/auth/google'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/checkout/success'
    | '/shop/$productId'
    | '/admin'
    | '/shop'
    | '/api/auth/$'
    | '/shop/$productId/customize'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/customize'
    | '/lifestyle'
    | '/location'
    | '/login'
    | '/overview'
    | '/philosophy'
    | '/shop'
    | '/signup'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/orders'
    | '/auth/google'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/signup'
    | '/checkout/success'
    | '/shop/$productId'
    | '/admin/'
    | '/shop/'
    | '/api/auth/$'
    | '/shop/$productId/customize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomizeRoute: typeof CustomizeRoute
  LifestyleRoute: typeof LifestyleRoute
  LocationRoute: typeof LocationRoute
  LoginRoute: typeof LoginRoute
  OverviewRoute: typeof OverviewRoute
  PhilosophyRoute: typeof PhilosophyRoute
  ShopRoute: typeof ShopRouteWithChildren
  SignupRoute: typeof SignupRoute
  AuthGoogleRoute: typeof AuthGoogleRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lifestyle': {
      id: '/lifestyle'
      path: '/lifestyle'
      fullPath: '/lifestyle'
      preLoaderRoute: typeof LifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/philosophy': {
      id: '/philosophy'
      path: '/philosophy'
      fullPath: '/philosophy'
      preLoaderRoute: typeof PhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/google': {
      id: '/auth/google'
      path: '/auth/google'
      fullPath: '/auth/google'
      preLoaderRoute: typeof AuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/auth/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$productId/customize': {
      id: '/shop/$productId/customize'
      path: '/customize'
      fullPath: '/shop/$productId/customize'
      preLoaderRoute: typeof ShopProductIdCustomizeRouteImport
      parentRoute: typeof ShopProductIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface ShopProductIdRouteChildren {
  ShopProductIdCustomizeRoute: typeof ShopProductIdCustomizeRoute
}

const ShopProductIdRouteChildren: ShopProductIdRouteChildren = {
  ShopProductIdCustomizeRoute: ShopProductIdCustomizeRoute,
}

const ShopProductIdRouteWithChildren = ShopProductIdRoute._addFileChildren(
  ShopProductIdRouteChildren,
)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomizeRoute: CustomizeRoute,
  LifestyleRoute: LifestyleRoute,
  LocationRoute: LocationRoute,
  LoginRoute: LoginRoute,
  OverviewRoute: OverviewRoute,
  PhilosophyRoute: PhilosophyRoute,
  ShopRoute: ShopRouteWithChildren,
  SignupRoute: SignupRoute,
  AuthGoogleRoute: AuthGoogleRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
